version: '3'

services:

    nginx: #docker-compose run -d nginx
        container_name: nginx_http
        restart: unless-stopped
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/init.conf:/etc/nginx/nginx.conf
    
    certbot: #docker-compose run -d certbot
        image: certbot/certbot
        container_name: certbot
        volumes: 
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email {email} -d {domain} --agree-tos

    nginxssl: #docker-compose run -d nginxssl
        container_name: nginx
        restart: unless-stopped
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot